### ISSUE TITLE
Cannot execute xsl:result-document while evaluating xsl:variable

### ISSUE THREAD

**Issue by stefan-jung** [dita-community/org.dita-community.split-page-sequences#5] opened 2022-05-19 10:59 UTC
When I try to build, it fails with this error:

```
    [exec] transform.topic2fo.main:
     [exec]  [pipeline] Loading stylesheet C:\Users\eike\AppData\Roaming\Dometic\DITA\dita-ot\plugins\org.dita.pdf2.fop\xsl\fo\topic2fo_shell_fop.xsl
     [exec]  [pipeline] Warning at xsl:stylesheet on line 12 column 17 of split-page-sequences.xsl:
     [exec]  [pipeline]   Stylesheet module
     [exec]  [pipeline]   file:/C:/Users/eike/AppData/Roaming/Dometic/DITA/dita-ot/plugins/org.dita-community.split-page-sequences/cfg/fo/xsl/split-page-sequences.xsl is included or imported more than once. This is permitted, but may lead to errors or unexpected behavior
     [exec]  [pipeline] Warning at xsl:stylesheet on line 12 column 17 of topic.xsl:
     [exec]  [pipeline]   Stylesheet module
     [exec]  [pipeline]   file:/C:/Users/eike/AppData/Roaming/Dometic/DITA/dita-ot/plugins/org.dita-community.split-page-sequences/cfg/fo/xsl/topic.xsl is included or imported more than once. This is permitted, but may lead to errors or unexpected behavior
     [exec]  [pipeline] Processing file:/C:/Users/eike/workspace/com.dometic.dita-ot-pdf/test-files/split-page-sequences/temp/stage1.xml to file:/C:/Users/eike/workspace/com.dometic.dita-ot-pdf/test-files/split-page-sequences/temp/stage2.fo
     [exec]  [pipeline] Error in xsl:result-document/@href on line 32 column 44 of root-processing.xsl:
     [exec]  [pipeline]   XTDE1480: Cannot execute xsl:result-document while evaluating xsl:variable
     [exec]  [pipeline]   In template rule with match="/" on line 22 of root-processing.xsl
     [exec]  [pipeline]      invoked by xsl:next-match at file:/C:/Users/eike/AppData/Roaming/Dometic/DITA/dita-ot/plugins/org.dita-community.split-page-sequences/cfg/fo/xsl/root-processing.xsl#27
     [exec]  [pipeline]   In template rule with match="/" on line 22 of root-processing.xsl
     [exec]  [pipeline] Failed to transform document: Failed to transform document: Cannot execute xsl:result-document while evaluating xsl:variable
     [exec] Error: The following error occurred while executing this line:
     [exec] C:\Users\eike\AppData\Roaming\Dometic\DITA\dita-ot\plugins\org.dita.pdf2\build.xml:384: java.io.IOException: Failed to read document: C:\Users\eike\workspace\com.dometic.dita-ot-pdf\test-files\split-page-sequences\temp\stage2.fo (The system cannot find the file specified)
     [exec]  [pipeline] + [DEBUG] SPS: Applying templates to base FO in mode sps:split-page-sequences...
```

**Comment by drmacro** [comment] 2022-05-27 16:51
Definitely a coding error on my part. I will correct.

**Comment by drmacro** [comment] 2022-05-27 17:23
How did you run OT to get this failure?

**Comment by drmacro** [comment] 2022-05-27 17:28
The error is caused by this code in the split-page-sequences override of the root template from the base PDF2 root-processing.xsl:

```
    <xsl:result-document href="base-fo.fo">
      <xsl:sequence select="$base-fo"/>
    </xsl:result-document>
```

This is just for debugging purposes and can be safely removed.

However, I don't see a way using the normal PDF2 transform that this error could occur, as it will only occur if something is trying to put the result of the root-processing "/" template into a variable. In that case, attempting to write to an intermediate file will definitely cause the error reported.

But since I do not get this failure in my normal testing my conclusion is that some other custom code must be putting the root-processing output into a variable.

I will remove the result-document instruction since it's not needed.

**Comment by stefan-jung** [comment] 2022-05-27 17:34
By publishing a DITA-OT project file via oXygen  XML. I tried to integrate the plugin but was not sure if I had to add it to the FOP shell.

**Comment by drmacro** [comment] 2022-05-27 17:34
Fix committed on develop branch.

**Closed as completed by drmacro** 2022-05-27 17:34 UTC
Labels: bug

**Comment by drmacro** [comment] 2022-05-27 17:36
You should only need to install the plugin, which you can do by copying the plugin dir to dita-ot/plugins and then running the dita --install command.

I'm also setting it up to be published via the registry and creating a release Zip file.
